### ISSUE TITLE
微服务可以通过mesher访问外部http服务吗？

### ISSUE THREAD

**Issue by sundayslove** [go-mesh/mesher#36]
mesher对接的微服务如何访问外部服务呢？

访问内部服务时，url中直接填服务名就行，mesher的负载均衡模块会将服务名映射为ip:port。

那如果是外部服务呢，如果url中填的是外部的域名(http://github.com/......)，此时能通过mesher代理请求吗？

**Comment by tianxiaoliang** [comment]
https://mesher.readthedocs.io/en/latest/istio/egress.html

**Comment by sundayslove** [comment]
简单看了一下代码，mesher貌似是优先给服务名匹配egress调用链，没匹配上再去匹配consumer调用链。

然后go-chassis中有提供相似的功能吗？看了一下，好像go-chassis中egress相关的功能还没有实现？

**Comment by tianxiaoliang** [comment]
是的，go chassis并没有egress流量管理

**Comment by tianxiaoliang** [comment]
就用https://github.com/go-chassis/go-chassis/tree/master/pkg/httpclient

**Comment by sundayslove** [comment]
好的，谢谢解答
